export const ROLES = {
  ADMIN: 'admin',
  CUSTOMER: 'customer',
  POLYTUNNEL_MANAGER: 'polytunnelManager',
  INVENTORY_MANAGER: 'inventoryManager',
  ORDER_MANAGER: 'orderManager',
  USER_CUSTOMER_MANAGER: 'userCustomerManager',
};

export const ADMIN_AREA_ROLES = [
  ROLES.ADMIN,
  ROLES.POLYTUNNEL_MANAGER,
  ROLES.INVENTORY_MANAGER,
  ROLES.ORDER_MANAGER,
  ROLES.USER_CUSTOMER_MANAGER,
];

export const ADMIN_MODULE_ROLES = {
  polytunnels: [ROLES.ADMIN, ROLES.POLYTUNNEL_MANAGER],
  inventory: [ROLES.ADMIN, ROLES.INVENTORY_MANAGER],
  orders: [ROLES.ADMIN, ROLES.ORDER_MANAGER],
  deliveries: [ROLES.ADMIN, ROLES.USER_CUSTOMER_MANAGER],
  users: [ROLES.ADMIN, ROLES.USER_CUSTOMER_MANAGER],
};

export const ALL_AUTH_ROLES = [
  ROLES.ADMIN,
  ROLES.CUSTOMER,
  ROLES.POLYTUNNEL_MANAGER,
  ROLES.INVENTORY_MANAGER,
  ROLES.ORDER_MANAGER,
  ROLES.USER_CUSTOMER_MANAGER,
];
